[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc:main"

[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin:main"

[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin:main"

# Install Python3 in all containers
[target.'cfg(all())'.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "GITHUB_TOKEN",
]
