[target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile.aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu.env]
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER = "aarch64-linux-gnu-gcc"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS = "-L /usr/lib/aarch64-linux-gnu -L /usr/aarch64-linux-gnu/lib"
PKG_CONFIG_ALLOW_CROSS = "1"
