# Rustfmt configuration
# See all options at: https://rust-lang.github.io/rustfmt/

# Basic settings
max_width = 100
tab_spaces = 4
edition = "2024"
newline_style = "Unix"

# Code structure
reorder_imports = true
reorder_modules = true

# Unstable features (only available in nightly)
# To use these, switch to nightly channel: rustup default nightly
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# reorder_impl_items = true
# wrap_comments = true
# comment_width = 100
# normalize_comments = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_macro_bodies = true
# format_strings = true
